FROM node:20-alpine
WORKDIR /app

COPY shared ./shared
COPY client ./client

WORKDIR /app/shared
RUN npm install && npm run build

WORKDIR /app/client
RUN npm install

EXPOSE 3000
CMD ["npm", "run", "dev"]
