FROM node:20-alpine
WORKDIR /app

COPY shared ./shared
COPY server ./server

WORKDIR /app/shared
RUN npm install && npm run build

WORKDIR /app/server
RUN npm install
RUN npx prisma generate

EXPOSE 5000
CMD ["npm", "run", "dev"]
